server:
  port: 80

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Enable discovery locator to route requests to services registered with Eureka
          lower-case-service-id: true  # Optional: Lowercases service IDs for routing purposes
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/