spring:
  application:
    name: service2
  datasource:
    url: jdbc:postgresql://localhost:5432/service2_db
    username: root
    password: dennis
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
