server:
  port: 8761 # Default port for Eureka Server

eureka:
  instance:
    hostname: localhost # Set the hostname of your Eureka Server
  client:
    register-with-eureka: false # Eureka Server should not register with itself
    fetch-registry: false # Eureka Server does not need to fetch registry